### ISSUE TITLE
Autoload.php

### ISSUE THREAD

**Issue by sameer615** [rkaldung/otrs-gi-rest-php#1]
Hii Roy,

client.php includes a file i.e. 'vendor/autoload.php';

i think file doesn't exist in project.

Thanks & Regards 
sameer

**Comment by rkaldung** [comment]
It will exist after you run composer update

**Comment by sameer615** [comment]
its throwing this error

 Fatal error: Uncaught exception 'Unirest\Exception' with message **'couldn't connect to host'** in /var/www/html/osa/myclient/vendor/mashape/unirest-php/src/Unirest/Request.php:476 Stack trace: #0 /var/www/html/osa/myclient/vendor/mashape/unirest-php/src/Unirest/Request.php(292): Unirest\Request::send('POST', 'https://192.168...', '{"UserLogin":"s...', Array, NULL, NULL) #1 /var/www/html/osa/myclient/client.php(26): Unirest\Request::post('https://192.168...', Array, '{"UserLogin":"s...') #2 {main} thrown in /var/www/html/osa/myclient/vendor/mashape/unirest-php/src/Unirest/Request.php on line 476


could you please explain this error****

**Comment by rkaldung** [comment]
Could not connect to host https://192.168.

- Check the protocol (http vs. https) in your environment
- Check if the server is reachable for the script

**Comment by sameer615** [comment]
hiiii @rkaldung ,

Thanks for the above help.
I've tried SOAP RPC to create ticket in OTRS 5.0.x

But I couldn't send dynamic field with SOAP RPC . 
so as suggested to Use GenericInterface , im using Generic Interface REST.

now i can create , search, update ticket with REST but not getting any idea to create ticket with dynamic field ....

kindly help me in that ....... i would be very thankful 

Thanks in advance

**Comment by rkaldung** [comment]
Hi @sameer615 
Here you find the documenation: http://doc.otrs.com/doc/api/otrs/stable/Perl/Kernel/GenericInterface/Operation/Ticket/TicketCreate.pm.html

You have to extend the [body](https://github.com/rkaldung/otrs-gi-rest-php/blob/master/client.php#L38) with a DynamicField as describe in the API.
